[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/api/v1/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200